### ISSUE TITLE
Post command on MacOS not working

### ISSUE THREAD

**Issue by TheBartoMan** [WarmUpTill/SceneSwitcher#1352]
### Operating System Info

Windows 11

### Other OS

MacOs

### OBS Studio Version

31.0.3

### Advanced Scene Switcher Version

1.29.3

### Expected Behavior

I am trying to do a very simple post command, doesn't need any headers etc.

The command works perfectly via curl or Postman, but SceneSwitcher doesn't do anything.

The log file looks like it runs with no errors.

I even tried switching from a HTTP action to a run action and running the curl command. also didn't work. 

### Current Behavior

the action executes, i see it flash green, but the post command doesn't look like it working,

### Steps to Reproduce

1.
2.
3.
...

### Anything else we should know?

![Image](https://github.com/user-attachments/assets/66a3e6d4-8165-412e-94c0-e7c608977870)

**Comment by WarmUpTill** [comment]
Can you try adjusting the URL to `http://192.168.1.167:8123` and the path to `/api/webhook/obsalert`?
I _assume_ that the URL can simply not be resolved.

**Comment by TheBartoMan** [comment]
@WarmUpTill with it all in the url, the error is "Could not establish connection"

with /api/webhook/obsalert in the path the error is "Failed to write connection"

From terminal (on same macbook as OBS), if i run "curl -X POST http://192.168.1.167:8123/api/webhook/obsalert" it works perfect

**Comment by WarmUpTill** [comment]
Thank you for notifying me about this problem!

While I don't fully understand what is causing the problem I _think_ I was able to find a solution.
A build with a fix is available here:
https://github.com/WarmUpTill/SceneSwitcher/actions/runs/14674399709/job/41187909725?pr=1353
(You will have to be logged into GitHub to be able to download it)

Can you confirm that this fix resolves the problems on your side?

**Comment by TheBartoMan** [comment]
I installed the MacOS version you posted which now shows as 1.29.3-14-g084660bc

Unfortunately the error is still the same, it flashes green as you it executed, but its not actually doing the POST

**Comment by WarmUpTill** [comment]
That is unfortunate, as I am at a bit off a loss as to what the problem might be.

Would you mind doing me a favour and, instead of connecting to your intended target, connect to a python http server, which prints out all of the connection details for incoming connections?

This is the content of the python script:
```
from http.server import HTTPServer, BaseHTTPRequestHandler
import time

class LoggingHTTPServer(HTTPServer):
    def finish_request(self, request, client_address):
        print(f"\n*** New connection from {client_address[0]}:{client_address[1]} ***")
        super().finish_request(request, client_address)

class RequestLoggerHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.log_request_details()
        self.send_response(200)
        self.end_headers()
        self.wfile.write(b'{"data": "test"}')
    
    def do_POST(self):
        self.log_request_details()
        content_length = int(self.headers.get('Content-Length', 0))
        body = self.rfile.read(content_length) if content_length else b''
        print("Body:", body.decode('utf-8', errors='replace'))
        
        self.send_response(200)
        self.end_headers()
        self.wfile.write(b"Request received")

    def do_PUT(self):
        self.do_POST()
    
    def do_DELETE(self):
        self.do_GET()
    
    def log_request_details(self):
        print("\n--- Incoming Request ---")
        print(f"Method: {self.command}")
        print(f"Path: {self.path}")
        print("Headers:")
        for key, value in self.headers.items():
            print(f"  {key}: {value}")
        print("------------------------")

if __name__ == "__main__":
    server_address = ('', 8182)
    httpd = LoggingHTTPServer(server_address, RequestLoggerHandler)
    print("Starting server on port 8182...")
    httpd.serve_forever()
```

I would be interested what this test server says about the connection attempts in your setup.

Here is an example of what this might look like:
![Image](https://github.com/user-attachments/assets/cfec15ec-98d7-4a2a-bbb2-bd808879d769)

If you want to use the example macro you can use this import code:
```
AAALUXicxVbbbts4EP0VgU+7XSuxZDdx/JZ4XdRAm3rjNC+LoqClkcSNRAok5ToN8u87Q10s2W2KfdoYAcTDuXHmzJDPrOCRVobN/35mkhfA5my550WZAxuxVKuqZPOE5wZGrOSVgQ3fwQ1kfCeUZvNxg/ZkNM9zyDtAyUXGZYoSVle4No+iXO4h+iQ3lmvbyRmryuvICiXNKrlV9k8lD1bJb6a0XQgdVcIudzyvOMn2JRYV2igWSsaCthYZRI8raUGjdCcXvSr0zMgy9D7GZ+HV0d+I2aeStl7QrRTWZWEH2rh4AkRjFT1uwFohU0O2NKTCoI8uioybu0reVNaSSp0YxNaUyhMU82Qr84Fve1nNRJrl+G9XSXcWc6+rQ8p0a/8e9hgiQ3+sKdYAdz4ZneR073ON4W40cFJH1Agd/Htcg0dhnw003lFAr6m4iEmH8raKUYDHO2N8x0yfQH8yiWE2u3zrR2/5zJ8mk6nPL3noJ5dX4WQ74/wqHLOjKjj1mlKdw02ZC4uVWCsjav4g7Uuif4gqzefkavrypdFfYmi1jZ+rTi7CTndMmm293yv7CE9m2EA1iNpfuqT3IavSNIf1MXxIZ73mUbt4ZgbSAqTtMy5Sec5LA/FpgwyJFPUx9vHJy93niIHk25z0ax4OMiuoRpm15dddSNTRpBuEl2dj/AXzWTALHddshvg5N3FSE8JilPeudxgvMZ2R6+Hzf4wibm5V/EQ7KN6oGLDvgcfo+kD8do3nrr9R5bqyOB3E93okUC26rRtAhmkvCCdDfJELDMZHtg1gnpiYJ/wbMKoj+l/jPCvMYLwVtXf3iSqYWP1V1HZazLkjCgEGFrsBEVe6mVinQybAvP1qqpD5/6fQO64FiVB/NZ+39UWhwVZa9vCw2VhJPJmIvRb3DOTgGEtVtfqhPjfDlayKh5OZO8hGR32M6WLUJmEV79ncD3BdbTdWYz6a++Rgpm/kICW+w8+EsG9hv+bU5eiMnb1hDfaR2yhzHn+smAgZ35EgCdQJ7VPGit4NpMqmc1tFjAud0Wj0rPIIcW7LnEcw3GtA75vAzmpCw9GWiPQ1v3VdB24LbM3lvtRg6lqz37zA+8MLvTfexPvdO/emrEektVZFebiphSwr22LsGk2k0nNZoRjbks9rCysnTFFnKo97V6A42WC+D3QTexaP6/uOmjuhlaRyPwyZ93mzvFvffXq3+rAkRkUgYdNRDHPRlGbUPmmwO5mFokQzh+2QCL53Yo7obgAddYAzvULVlYyhX/+gX/9Y6Nb32BEcifYBZEoD8McaJY9jFMK3EQY0nSHLuYH7NmrNZayK26rYgj6h9bA7+qJLpE5/qhyJpngUHEJA752UMl4zg8bvXxXop7ohaXl82IGZXn5wxEF3QTY3kytsWy6HkdiuB3QPzTuOM8KdD4jzBp+W14c0xpDwKrfdrKAJ2Fekd6WE3HOU+C/a3dj6lUp3z2J6KmjO1x2fBfg2PJv4wdRPx7PpxcV4G7GXfwGDpddu
```

Let me know, if you have any questions or if that won't be possible!
And I apologise for not being able to solve this issue more quickly!

**Comment by TheBartoMan** [comment]
Not a problem at all, I will do all the testing you need. I really appreciate a developer who works hard on their product.

I ran it localy and used your example script to do a GET then a POST. Here is the results:

python3 httpserver.py 
Starting server on port 8182...

*** New connection from 127.0.0.1:50364 ***

--- Incoming Request ---
Method: GET
Path: /asdf
Headers:
  Accept: */*
  Connection: close
  Host: 127.0.0.1:8182
  User-Agent: cpp-httplib/0.13.3
------------------------
127.0.0.1 - - [28/Apr/2025 20:45:22] "GET /asdf HTTP/1.1" 200 -

*** New connection from 127.0.0.1:50372 ***

--- Incoming Request ---
Method: POST
Path: /asdf?
Headers:
  Accept: */*
  Connection: close
  Content-Length: 8
  Content-Type: application/json
  Host: 127.0.0.1:8182
  User-Agent: cpp-httplib/0.13.3
------------------------
Body: asdfasdf
127.0.0.1 - - [28/Apr/2025 20:45:43] "POST /asdf? HTTP/1.1" 200 -

**Comment by TheBartoMan** [comment]
I also ran the script on a remote windows server and did the same GET and POST commands to that server and got the same results.

**Comment by WarmUpTill** [comment]
Thanks for performing the test!

To me it *seems* like the http requests are being sent out the plug-in and received properly by the python http server.

What "type" of server are you trying to connect to, when the connection attempt fails?

Does a GET to "google.com" at "/" work?

**Comment by TheBartoMan** [comment]
i just created a shell script that contains:

_#!/bin/bash
curl -X POST http://192.168.1.167:8123/api/webhook/obsalert_

..when i run that as an action from your app it works fine (its a workaround but would love to know why it doesnt work)

The server is Home Assistant. https://www.home-assistant.io/docs/automation/trigger/#webhook-trigger

**Comment by WarmUpTill** [comment]
I just set up a VM with the Home Assistant software and I am able to send webhook requests successfully.

Here is the example hook I set up:

![Image](https://github.com/user-attachments/assets/7ef1560f-9b73-49bc-ae23-7686d2d24170)

This is the action I used:

![Image](https://github.com/user-attachments/assets/3f4e59a1-458b-4ac4-a27d-82086167f914)

And here it is in action:

![Image](https://github.com/user-attachments/assets/8a204ed1-f806-42c7-b80f-e839b7371b34)

It seems to be important to leave the "Message body" field empty or otherwise Home Assistant will ignore the request.
Can you confirm that behavior on your side?

**Comment by TheBartoMan** [comment]
I got it working, it was really fussy. I had to clear out the content type, the message and split the url into the separate path. **Thank you** very much for your time and effort, you went above and beyond.

I do have another issue that screenshots dont save to a custom file path only the default works. If this is not a known issue i can raise it?

**Comment by WarmUpTill** [comment]
I am glad to hear that you got it working!

>I do have another issue that screenshots dont save to a custom file path only the default works. If this is not a known issue i can raise it?

I am not aware of any issues in that regard.
Feel free to create a separate issue for that topic.
