### ISSUE TITLE
Current master (77fe75f) doesn't honor BUILD_OUT_OF_TREE

### ISSUE THREAD

**Issue by eribertomota** [WarmUpTill/SceneSwitcher#548]
Hi @WarmUpTill,

I am opening a new issue to report issues when packaging master on Debian (a test only, before a new plugin release).

I have in my debian/rules:

```
# Exclude "obs-" from NAME and set a DEST
export PLUGIN_NAME=$(shell echo ${DEB_SOURCE} | cut -d"-" -f2-)
export PLUGIN_DEST=debian/${DEB_SOURCE}/usr/lib/${DEB_TARGET_MULTIARCH}/obs-plugins

%:
        dh $@

override_dh_auto_configure:
        dh_auto_configure -- -DBUILD_OUT_OF_TREE=1 \
                             -DLIBOBS_INCLUDE_DIR=/usr/include/obs \
                             -DLIBOBS_LIB=/usr/lib/${DEB_TARGET_MULTIARCH}/libobs.so \
                             -DLIBOBS_FRONTEND_INCLUDE_DIR=/usr/include/obs \
                             -DLIBOBS_FRONTEND_API_LIB=/usr/lib/${DEB_TARGET_MULTIARCH}/libobs-frontend-api.so \
                             -DLIB_OUT_DIR=lib/${DEB_TARGET_MULTIARCH}/obs-plugins \
                             -DDATA_OUT_DIR=share/obs/obs-plugins/$(PLUGIN_NAME)
```

However, after building, I can see:

```
└── usr
    ├── data
    │   └── obs-plugins
    │       └── advanced-scene-switcher
    │           ├── locale
    │           │   ├── de-DE.ini
    │           │   ├── en-US.ini
    │           │   ├── es-ES.ini
    │           │   ├── ru-RU.ini
    │           │   ├── tr-TR.ini
    │           │   └── zh-CN.ini
    │           └── res
    │               ├── cascadeClassifiers
    │               │   ├── haarcascade_eye.xml
    │               │   ├── haarcascade_eye_tree_eyeglasses.xml
    │               │   ├── haarcascade_frontalface_alt.xml
    │               │   ├── haarcascade_frontalface_alt2.xml
    │               │   ├── haarcascade_frontalface_alt_tree.xml
    │               │   ├── haarcascade_frontalface_default.xml
    │               │   ├── haarcascade_fullbody.xml
    │               │   ├── haarcascade_lefteye_2splits.xml
    │               │   ├── haarcascade_lowerbody.xml
    │               │   ├── haarcascade_profileface.xml
    │               │   ├── haarcascade_righteye_2splits.xml
    │               │   └── haarcascade_upperbody.xml
    │               └── time.svg
    └── obs-plugins
        └── 64bit
            ├── adv-ss-plugins
            │   └── advanced-scene-switcher-opencv.so
            ├── advanced-scene-switcher-lib.so
            └── advanced-scene-switcher.so
```

Could you check this behavior, please?

Cheers,

Eriberto

**Comment by eribertomota** [comment]
As an additional information, I had a problem with RPATH, but I think that it will be solved after a fixing for BUILD_OUT_OF_TREE.

```
dpkg-shlibdeps: warning: cannot find library advanced-scene-switcher-lib.so needed by debian/obs-advanced-scene-switcher/usr/lib/x86_64-linux-gnu/obs-plugins/advanced-scene-switcher.so (ELF format: 'elf64-x86-64' abi: '0201003e00000000'; RPATH: '')

E: obs-advanced-scene-switcher: custom-library-search-path RUNPATH /usr/bin/64bit [usr/lib/x86_64-linux-gnu/obs-plugins/adv-ss-plugins/advanced-scene-switcher-opencv.so]
```

**Comment by WarmUpTill** [comment]
Hi @eribertomota,

I made some slight adjustments with the linked PR.
I think you can **remove** the following parameters:
```
-DBUILD_OUT_OF_TREE=1
```
This will automatically be detected.
But manually specifying it shouldn't break anything.

You will have to *add* the following parameters:
```
-DDEB_INSTALL=ON
-DLINUX_PORTABLE=OFF
-DCMAKE_INSTALL_PREFIX=/usr
```

This should result in the desired file  / folder structure.

Tested with the following build:
```
cmake \
    -DLIBOBS_LIB=~/obs-studio/plugin_build_x86_64/libobs/libobs.so \
    -DLIBOBS_INCLUDE_DIR=~/obs-studio/libobs/ \
    -DLIBOBS_FRONTEND_API_LIB=~/obs-studio/plugin_build_x86_64/UI/obs-frontend-api/libobs-frontend-api.so \
    -DLIBOBS_FRONTEND_INCLUDE_DIR=~/obs-studio/UI/obs-frontend-api/ \
    -DCMAKE_INSTALL_PREFIX=~/tmp/usr \
    -DLINUX_PORTABLE=OFF \
    -DDEB_INSTALL=ON \
    -DLIB_OUT_DIR=lib/some-extra-fodler/obs-plugins \
    -DDATA_OUT_DIR=share/obs/obs-plugins/advanced-scene-switcher \
    ..
```
Which produced the following output:
```
till@ubuntu:~/SceneSwitcher$ tree ~/tmp/
/home/till/tmp/
└── usr
    ├── lib
    │   └── some-extra-fodler
    │       └── obs-plugins
    │           ├── advanced-scene-switcher-lib.so
    │           ├── adv-ss-plugins
    │           │   └── advanced-scene-switcher-opencv.so
    │           └── libadvanced-scene-switcher.so
    └── share
        └── obs
            └── obs-plugins
                └── advanced-scene-switcher
                    ├── locale
                    │   ├── de-DE.ini
                    │   ├── en-US.ini
                    │   ├── es-ES.ini
                    │   ├── ru-RU.ini
                    │   ├── tr-TR.ini
                    │   └── zh-CN.ini
                    └── res
                        ├── cascadeClassifiers
                        │   ├── haarcascade_eye_tree_eyeglasses.xml
                        │   ├── haarcascade_eye.xml
                        │   ├── haarcascade_frontalface_alt2.xml
                        │   ├── haarcascade_frontalface_alt_tree.xml
                        │   ├── haarcascade_frontalface_alt.xml
                        │   ├── haarcascade_frontalface_default.xml
                        │   ├── haarcascade_fullbody.xml
                        │   ├── haarcascade_lefteye_2splits.xml
                        │   ├── haarcascade_lowerbody.xml
                        │   ├── haarcascade_profileface.xml
                        │   ├── haarcascade_righteye_2splits.xml
                        │   └── haarcascade_upperbody.xml
                        └── time.svg

```

Let me know if this resolves your issue.

By the will I will probably release version 1.18.1 soon, in case you want to wait for that before releasing the next version of the Debian package.

**Comment by WarmUpTill** [comment]
I merged the changes for now - let me know if you need further adjustments :)

**Comment by eribertomota** [comment]
Hi @WarmUpTill,

The final files are being installed in right directories now. Thanks for the fix. However, I still getting these lines:

```
   dh_shlibdeps -a
dpkg-shlibdeps: warning: cannot find library advanced-scene-switcher-lib.so needed by debian/obs-advanced-scene-switcher/usr/lib/x86_64-linux-gnu/obs-plugins/libadvanced-scene-switcher.so (ELF format: 'elf64-x86-64' abi: '0201003e00000000'; RPATH: '')
dpkg-shlibdeps: warning: cannot find library advanced-scene-switcher-lib.so needed by debian/obs-advanced-scene-switcher/usr/lib/x86_64-linux-gnu/obs-plugins/adv-ss-plugins/advanced-scene-switcher-opencv.so (ELF format: 'elf64-x86-64' abi: '0201003e00000000'; RPATH: '/usr/lib')
```

The following Debian lintian is being shown to explain the situation:

`E: obs-advanced-scene-switcher: custom-library-search-path RUNPATH /usr/lib [usr/lib/x86_64-linux-gnu/obs-plugins/adv-ss-plugins/advanced-scene-switcher-opencv.so]`

You can see more about this lintian here[1]. I couldn't move files do /usr/lib/ or /usr/lib/obs-advanced-scene-switcher/ because the files must be put in usr/lib<arch>/obs-plugins/

Could you help me with this issue?

[1] https://lintian.debian.org/tags/custom-library-search-path

**Comment by eribertomota** [comment]
Doing some tests:

```
# ldd /usr/lib/x86_64-linux-gnu/obs-plugins/libadvanced-scene-switcher.so |grep advanced
        advanced-scene-switcher-lib.so => not found
```

**Comment by WarmUpTill** [comment]
Is there a way I can reproduce these issues on my end somehow?
To be honest I am a bit puzzled where `advanced-scene-switcher-lib.so` is coming from.
I think something is causing `advanced-scene-switcher-lib.so` to be used in place of `libadvanced-scene-switcher.so` and that is likely the problem.

**Comment by eribertomota** [comment]
Do you remember about how to create a jail based on Debian Unstable? If yes, I think I can send you the package.

**Comment by WarmUpTill** [comment]
Yes, right!
I will set up a VM quickly and give it a try.

**Comment by eribertomota** [comment]
I sent a private email message for you, but you can send me any doubt here.

**Comment by WarmUpTill** [comment]
Ah I understand now.
`libadvanced-scene-switcher.so` is the module to be loaded by OBS.

I _attempted_ to resolve the problem with the linked PR.
I no longer observed this rpath warning when running `dpkg-buildpackage -b`.

Let me know if there is anything else. :)

**Comment by eribertomota** [comment]
I will check now

**Comment by eribertomota** [comment]
I am testing OBS + SceneSwitcher on Debian Testing (OBS 28.0.1.11). Without SceneSwitcher, OBS starts fine. With SceneSwitcher, OBS breaks. The last messages in log are:

```
info: [adv-ss] version: debian/1.17.7-1-5-ge6b73dd
info: [adv-ss] version: e6b73dd60b25dfa8d60491f7c2434bf574296a52
info: [adv-ss] curl loaded successfully
info: [adv-ss] found curl library
info: [adv-ss] attempting to load "/usr/lib/x86_64-linux-gnu/obs-plugins/adv-ss-plugins/advanced-scene-switcher-opencv.so"
info: [adv-ss] successfully loaded "/usr/lib/x86_64-linux-gnu/obs-plugins/adv-ss-plugins/advanced-scene-switcher-opencv.so"
QWidget: Must construct a QApplication before a QWidget
Aborted
```

**Comment by eribertomota** [comment]
Also, I can see the following abnormal warning from dpkg-shlibdeps:

`dpkg-shlibdeps: warning: can't extract name and version from library name 'advanced-scene-switcher-lib.so'`

Maybe the objdump command may help you on this issue.

**Comment by WarmUpTill** [comment]
> dpkg-shlibdeps: warning: can't extract name and version from library name 'advanced-scene-switcher-lib.so'

Probably harmless but I set the version to "1" just in case in the linked PR.

> I am testing OBS + SceneSwitcher on Debian Testing (OBS 28.0.1.11). Without SceneSwitcher, OBS starts fine. With SceneSwitcher, OBS breaks. The last messages in log are:
> 
> ```
> info: [adv-ss] version: debian/1.17.7-1-5-ge6b73dd
> info: [adv-ss] version: e6b73dd60b25dfa8d60491f7c2434bf574296a52
> info: [adv-ss] curl loaded successfully
> info: [adv-ss] found curl library
> info: [adv-ss] attempting to load "/usr/lib/x86_64-linux-gnu/obs-plugins/adv-ss-plugins/advanced-scene-switcher-opencv.so"
> info: [adv-ss] successfully loaded "/usr/lib/x86_64-linux-gnu/obs-plugins/adv-ss-plugins/advanced-scene-switcher-opencv.so"
> QWidget: Must construct a QApplication before a QWidget
> Aborted
> ```

I am not able to reproduce this issue.
OBS boots up just fine with or without the plugin.

![SS](https://user-images.githubusercontent.com/19472752/193531977-5c5fd630-071d-4208-8623-155280758d65.PNG)

I did however have to pass `QT_QTA_PLATFORM=xcb` for OBS to start up at all.
Are you using an empty scene collection or have you already configured something on the plugin side?

**Comment by eribertomota** [comment]
> > dpkg-shlibdeps: warning: can't extract name and version from library name 'advanced-scene-switcher-lib.so'
> 
> Probably harmless but I set the version to "1" just in case in the linked PR.


Fixed. Thanks.


> 
> I did however have to pass `QT_QTA_PLATFORM=xcb` for OBS to start up at all. Are you using an empty scene collection or have you already configured something on the plugin side?

QT_QTA_PLATFORM=xcb doesn't solve the issue. I did some tests and I noticed that plugin works fine if built with qt5. However, using qt6 causes an abnormal exit when starting OBS. Ideas???

**Comment by WarmUpTill** [comment]
>However, using qt6 causes an abnormal exit when starting OBS. Ideas???

To be honest I am at a loss what could be causing this. :(
I built OBS from source with Qt6 but I cannot observe this problem.

Can you maybe attach a debugger and check which line is causing the issue?
I will try to reproduce the abort further in different environments.

**Comment by eribertomota** [comment]
I found the problem. On Debian, OBS Studio 28 is being built with qt5[1]. So I will use qt5 for SceneSwitcher too. I will make the final tests tomorrow.

[1] https://tracker.debian.org/media/packages/o/obs-studio/control-28.0.1dfsg1-3

**Comment by eribertomota** [comment]
Hi @WarmUpTill,

Hi confirm that SceneSwitcher is working fine over OBS 26.1.2 (Debian Stable) and 28.0.1 (Debian Unstable/Testing). I just uploaded it to Debian.

Thanks a lot for your work and help.
